version: '3.8'

services:
  web:
    image: ${WEB_IMAGE}
    pull_policy: always
    # build:
    #   context: ./web
    #   dockerfile: Dockerfile.web
    ports:
      - 80:8080
  backend:
    image: ${SERVER_IMAGE}
    pull_policy: always
    depends_on:
      - db
    # build:
    #   context: ./server
    #   dockerfile: Dockerfile.server
    environment:
      - DATABASE_URL="postgresql://postgres:postgres@db:5432/postgres?schema=public"
  db:
    image: postgres:17
    pull_policy: always
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
volumes:
  postgres-data:
