FROM node:23-alpine as build


WORKDIR /opt/inventory
COPY ./web ./
RUN apk update && npm i -g vite && npm install && npm run build

FROM nginx:1-alpine

COPY --from=build /opt/inventory/dist /usr/share/nginx/html
COPY ./web/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
