apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}-web
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  config.js: |-
    var BASE_URL = '{{ .Values.web.apiUrl }}';
