---
{{- if and .Values.postgres.persistence.enabled (not .Values.postgres.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "helm.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.postgres.persistence.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/component: postgres
    app.kubernetes.io/part-of: FRC-Inventory
    {{- include "helm.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.postgres.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size | quote }}
{{- if .Values.postgres.persistence.storageClass }}
{{- if (eq "-" .Values.postgres.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.postgres.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
