apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-server
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: FRC Inventory
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: FRC Inventory
