apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-web
  labels:
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: FRC-Inventory
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: FRC-Inventory
