---
authentication:
  google:
    enabled: true
web:
  websiteTitle: FRC 5572 Inventory
  image:
    pullPolicy: Always
server:
  image:
    pullPolicy: Always
postgres:
  persistenc:
    enabled: true
    storageClassName: local-path
ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-mw-admin@kubernetescrd
